# coding:utf-8

def get_lowercase(word):
    print(word.lower())

def get_convert_dict():
    convert_dictionary = {}
    convert_dictionary["feedback"] = "feedback"
    convert_dictionary["banner"] = "banner"
    convert_dictionary["news"] = "news"
    convert_dictionary["active"] = "active"
    convert_dictionary["culturale"] = "cultural"
    convert_dictionary["culturali"] = "cultural"
    convert_dictionary["convenzione"] = "convention"
    convert_dictionary["convenzioni"] = "convention"
    convert_dictionary["agenzia"] = "agency"
    convert_dictionary["operatore"] = "operator"
    convert_dictionary["punto"] = "point"
    convert_dictionary["punti"] = "point"
    convert_dictionary["messaggi"] = "message"
    convert_dictionary["errore"] = "error"
    convert_dictionary["priorita"] = "priority"
    convert_dictionary["statistici"] = "statistics"
    convert_dictionary["avanzata"] = "advance"
    convert_dictionary["sito"] = "site"
    convert_dictionary["generiche"] = "general"
    convert_dictionary["visita"] = "visit"
    convert_dictionary["dati"] = "data"
    convert_dictionary["data_abcdefghijklmn"] = "data"
    convert_dictionary["data"] = "date"
    convert_dictionary["controllo"] = "control"
    convert_dictionary["controlla"] = "check"
    convert_dictionary["visite"] = "visit"
    convert_dictionary["costanti"] = "constant"
    convert_dictionary["globali"] = "global"
    convert_dictionary["connessione"] = "connection"
    convert_dictionary["ricerca"] = "search"
    convert_dictionary["statistiche"] = "statistics"
    convert_dictionary["localita"] = "location"
    convert_dictionary["locale"] = "location"
    convert_dictionary["local"] = "location"
    convert_dictionary["elenco"] = "list"
    convert_dictionary["categorie"] = "category"
    convert_dictionary["gestione"] = "management"
    convert_dictionary["comune"] = "common"
    convert_dictionary["turisti"] = "tourist"
    convert_dictionary["turista"] = "tourist"
    convert_dictionary["tourism"] = "tourist"
    convert_dictionary["voto"] = "vote"
    convert_dictionary["voti"] = "vote"
    convert_dictionary["testo"] = "text"
    convert_dictionary["modifica"] = "modify"
    convert_dictionary["ottieni"] = "get"
    convert_dictionary["descrizione"] = "description"
    convert_dictionary["telefono"] = "telephone"
    convert_dictionary["telephone"] = "phone"
    convert_dictionary["via"] = "street"
    convert_dictionary["path"] = "street"
    convert_dictionary["atti"] = "active"
    convert_dictionary["caratteristiche"] = "feature"
    convert_dictionary["features"] = "feature"
    convert_dictionary["autenticazione"] = "authentication"
    convert_dictionary["storico"] = "history"
    convert_dictionary["tema"] = "theme"
    convert_dictionary["subject"] = "theme"
    convert_dictionary["topic"] = "theme"
    convert_dictionary["numero"] = "number"
    convert_dictionary["ad"] = "advertisement"
    convert_dictionary["ie"] = "ie"
    convert_dictionary["disattiva"] = "disable"
    convert_dictionary["scheda"] = "card"
    convert_dictionary["ristoro"] = "refreshment"
    convert_dictionary["bene"] = "good"
    convert_dictionary["piatto"] = "plate"
    convert_dictionary["beni"] = "asset"
    convert_dictionary["di"] = "of"
    convert_dictionary["da"] = "from"
    convert_dictionary["pubblicazione"] = "publication"
    convert_dictionary["scadenza"] = "deadline"
    convert_dictionary["nom"] = "name"
    convert_dictionary["cognome"] = "name"
    convert_dictionary["nome"] = "name"
    convert_dictionary["utente"] = "user"
    convert_dictionary["tipologia"] = "type"
    convert_dictionary["parametro"] = "parameter"
    convert_dictionary["paramtro"] = "parameter"
    convert_dictionary["richiesta"] = "request"
    convert_dictionary["preferenza"] = "preference"
    convert_dictionary["preferenze"] = "preference"
    convert_dictionary["contentente"] = "contain"
    convert_dictionary["posizione"] = "position"
    convert_dictionary["provincia"] = "province"
    convert_dictionary["citta"] = "city"
    convert_dictionary["orario"] = "schedule"
    convert_dictionary["apertura"] = "open"
    convert_dictionary["chiusura"] = "close"
    convert_dictionary["giorno"] = "day"
    convert_dictionary["costo"] = "cost"
    convert_dictionary["biglietto"] = "ticket"
    convert_dictionary["media "] = "average"
    convert_dictionary["inizio"] = "start"
    convert_dictionary["fine"] = "end"
    convert_dictionary["prezzo"] = "price"
    convert_dictionary["dimensione"] = "dimension"
    convert_dictionary["tema"] = "theme"
    convert_dictionary["partita"] = "political"
    convert_dictionary["pva"] = "party"
    convert_dictionary["nascita"] = "birth"
    convert_dictionary["residenza"] = "residence"
    convert_dictionary["registrazione"] = "registration"
    convert_dictionary["attiva"] = "active"
    convert_dictionary["attivi"] = "active"
    convert_dictionary["apri"] = "open"
    convert_dictionary["commento"] = "comment"
    convert_dictionary["termini"] = "term"
    convert_dictionary["termine"] = "term"
    convert_dictionary["esiste"] = "exist"
    convert_dictionary["nulli"] = "null"
    convert_dictionary["stringa"] = "string"
    convert_dictionary["lettere"] = "letters"
    convert_dictionary["permesse"] = "permission"
    convert_dictionary["numeri"] = "number"
    convert_dictionary["caratteri"] = "character"
    convert_dictionary["necessari"] = "necessary"
    convert_dictionary["tagi"] = "tag"
    convert_dictionary["lista"] = "list"
    convert_dictionary["distanza "] = "distance"
    convert_dictionary["massima"] = "max"
    convert_dictionary["pagina"] = "page"
    convert_dictionary["elementi"] = "element"
    convert_dictionary["rilascia"] = "release"
    convert_dictionary["preferito"] = "favorite"
    convert_dictionary["nuovo"] = "new"
    convert_dictionary["nuova"] = "new"
    convert_dictionary["stato"] = "state"
    convert_dictionary["ultimi"] = "ultimate"
    convert_dictionary["indirizzo"] = "address"
    convert_dictionary["latitudine"] = "latitude"
    convert_dictionary["longitudine"] = "longitude"
    convert_dictionary["altitudine"] = "altitude"
    convert_dictionary["gradi"] = "degree"
    convert_dictionary["radianti"] = "radiant"
    convert_dictionary["parolechiave"] = "Keyword"
    convert_dictionary["raggio"] = "radius"
    convert_dictionary["documento"] = "document"
    convert_dictionary["visualizza"] = "visualize"
    convert_dictionary["return"] = "search"
    convert_dictionary["view"] = "search"
    convert_dictionary["get"] = "search"
    convert_dictionary["search"] = "search"
    convert_dictionary["show"] = "search"
    convert_dictionary["visualize"] = "search"
    convert_dictionary["insert"] = "insert"
    convert_dictionary["add"] = "insert"
    convert_dictionary["inserisci"] = "insert"
    convert_dictionary["aggiungi"] = "add"
    convert_dictionary["modify"] = "update"
    convert_dictionary["change"] = "update"
    convert_dictionary["update"] = "update"
    convert_dictionary["edit"] = "update"
    convert_dictionary["modificato"] = "modify"
    convert_dictionary["amend"] = "update"
    convert_dictionary["delete"] = "delete"
    convert_dictionary["elimina"] = "delete"
    convert_dictionary["eliminate"] = "delete"
    convert_dictionary["remove"] = "delete"
    convert_dictionary["cancella"] = "cancel"
    convert_dictionary["cancel"] = "delete"
    convert_dictionary["rimuovi"] = "remove"
    convert_dictionary["error"] = "error"
    convert_dictionary["wrong"] = "error"
    convert_dictionary["incorrect"] = "error"
    convert_dictionary["correggi"] = "error"
    convert_dictionary["eateries"] = "restaurant"
    convert_dictionary["immagine"] = "image"
    convert_dictionary["imagelcon"] = "image"
    convert_dictionary["arraylist"] = "list"
    convert_dictionary["parameters"] = "parameter"
    convert_dictionary["objects"] = "object"
    convert_dictionary["details"] = "detail"
    convert_dictionary["returns"] = "return"
    convert_dictionary["banners"] = "banner"
    convert_dictionary["refreshments"] = "refreshment"
    convert_dictionary["inserts"] = "insert"
    convert_dictionary["removes"] = "remove"
    convert_dictionary["tags"] = "tag"
    convert_dictionary["chooses"] = "choose"
    convert_dictionary["requires"] = "require"
    convert_dictionary["ensures"] = "ensure"
    convert_dictionary["privileges"] = "privilege"
    convert_dictionary["ends"] = "end"
    convert_dictionary["restaurants"] = "restaurant"
    convert_dictionary["preferences"] = "preference"
    convert_dictionary["favorites"] = "favorite"
    convert_dictionary["bookmarks"] = "bookmark"
    convert_dictionary["sites"] = "site"
    convert_dictionary["conventions"] = "convention"
    convert_dictionary["points"] = "point"
    convert_dictionary["realizes"] = "realize"
    convert_dictionary["contains"] = "contain"
    convert_dictionary["provides"] = "provide"
    convert_dictionary["represents"] = "represent"
    convert_dictionary["methods"] = "method"
    convert_dictionary["describes"] = "describe"
    convert_dictionary["characteristics"] = "characteristic"
    convert_dictionary["checks"] = "check"
    convert_dictionary["ratings"] = "rate"
    convert_dictionary["priorities"] = "priority"
    convert_dictionary["tourists"] = "tourist"
    convert_dictionary["types"] = "type"
    convert_dictionary["strings"] = "string"
    convert_dictionary["services"] = "service"
    convert_dictionary["constants"] = "constant"
    convert_dictionary["stubs"] = "stub"
    convert_dictionary["allows"] = "allow"
    convert_dictionary["actors"] = "actor"
    convert_dictionary["tasks"] = "task"
    convert_dictionary["operators"] = "operator"
    convert_dictionary["implements"] = "implement"
    convert_dictionary["extends"] = "extend"
    convert_dictionary["operations"] = "operate"
    convert_dictionary["users"] = "user"
    convert_dictionary["creates"] = "create"
    convert_dictionary["coordinates"] = "coordinate"
    convert_dictionary["radians"] = "radian"
    convert_dictionary["models"] = "model"
    convert_dictionary["components"] = "component"
    convert_dictionary["areas"] = "area"
    convert_dictionary["terms"] = "term"
    convert_dictionary["serves"] = "serve"
    convert_dictionary["values"] = "value"
    convert_dictionary["initializes"] = "initialize"
    convert_dictionary["sets"] = "set"
    convert_dictionary["dishes"] = "dish"
    convert_dictionary["visits"] = "visit"
    convert_dictionary["results"] = "result"
    convert_dictionary["elements"] = "element"
    convert_dictionary["pages"] = "page"
    convert_dictionary["degrees"] = "degree"
    convert_dictionary["columns"] = "column"
    convert_dictionary["determines"] = "determine"
    convert_dictionary["instantiates"] = "instantiate"
    convert_dictionary["votes"] = "vote"
    convert_dictionary["positions"] = "position"
    convert_dictionary["counters"] = "counter"
    convert_dictionary["selected"] = "select"
    convert_dictionary["included"] = "include"
    convert_dictionary["allowed"] = "allow"
    convert_dictionary["associated"] = "associate"
    convert_dictionary["designated"] = "designate"
    convert_dictionary["derived"] = "derive"
    convert_dictionary["registered"] = "register"
    convert_dictionary["supplied"] = "supply"
    convert_dictionary["involved"] = "involve"
    convert_dictionary["issued"] = "issue"
    convert_dictionary["advanced"] = "advance"
    convert_dictionary["confirmed"] = "confirm"
    convert_dictionary["offered"] = "offer"
    convert_dictionary["visited"] = "visit"
    convert_dictionary["released"] = "release"
    convert_dictionary["performed"] = "perform"
    convert_dictionary["inserted"] = "insert"
    convert_dictionary["limited"] = "limit"
    convert_dictionary["displayed"] = "display"
    convert_dictionary["received"] = "receive"
    convert_dictionary["represented"] = "represent"
    convert_dictionary["related"] = "relate"
    convert_dictionary["activated"] = "active"
    convert_dictionary["preferred"] = "prefer"
    convert_dictionary["made"] = "make"
    convert_dictionary["measured"] = "measure"
    convert_dictionary["passed"] = "pass"
    convert_dictionary["identified"] = "identify"
    convert_dictionary["stored"] = "store"
    convert_dictionary["pertaining"] = "pertain"
    convert_dictionary["relating"] = "relate"
    convert_dictionary["editing"] = "edit"
    convert_dictionary["searching"] = "search"
    convert_dictionary["existing"] = "exist"
    convert_dictionary["inserting"] = "insert"
    convert_dictionary["changing"] = "change"
    convert_dictionary["viewing"] = "view"
    convert_dictionary["using"] = "use"
    convert_dictionary["entering"] = "enter"
    convert_dictionary["replacing"] = "replace"
    convert_dictionary["containing"] = "contain"
    convert_dictionary["checking"] = "check"
    convert_dictionary["handling"] = "handle"
    convert_dictionary["managing"] = "manage"
    convert_dictionary["rating"] = "rate"
    convert_dictionary["displaying"] = "display"
    convert_dictionary["scrolling"] = "scroll"
    convert_dictionary["monitoring"] = "monitor"
    convert_dictionary["rendering"] = "render"
    convert_dictionary["testing"] = "test"
    convert_dictionary["implementing"] = "implement"
    convert_dictionary["extending"] = "extend"
    convert_dictionary["dining"] = "dine"
    convert_dictionary["returning"] = "return"
    convert_dictionary["describing"] = "describe"
    convert_dictionary["resting"] = "rest"
    convert_dictionary["opening"] = "open"
    convert_dictionary["closing"] = "close"
    convert_dictionary["voting"] = "vote"
    convert_dictionary["amending"] = "amend"
    convert_dictionary["updating"] = "update"
    convert_dictionary["setting"] = "set"
    convert_dictionary["obtaining"] = "obtain"
    convert_dictionary["catering"] = "cater"
    convert_dictionary["extracting"] = "extract"
    convert_dictionary["emerging"] = "emerge"
    convert_dictionary["collecting"] = "collect"
    convert_dictionary["creation"] = "create"
    convert_dictionary["registration"] = "register"
    convert_dictionary["communication"] = "communicate"
    convert_dictionary["calculation"] = "calculate"
    convert_dictionary["insertion"] = "insert"
    convert_dictionary["cancellation"] = "cancel"
    convert_dictionary["modification"] = "modify"
    convert_dictionary["extraction"] = "extract"
    convert_dictionary["scrollable"] = "scroll"
    convert_dictionary["functionality"] = "function"
    convert_dictionary["functionality"] = "function"
    convert_dictionary["functionality"] = "function"
    convert_dictionary["correctness"] = "correct"
    convert_dictionary["deployment"] = "deploy"
    convert_dictionary["agency's"] = "agency"
    convert_dictionary["dell'"] = "dell"
    convert_dictionary["container"] = "contain"
    convert_dictionary["management"] = "manage"
    convert_dictionary["operator"] = "operate"
    convert_dictionary["given"] = "give"
    convert_dictionary["handler"] = "handle"
    convert_dictionary["removal"] = "remove"
    convert_dictionary["intevallo"] = "interval"
    convert_dictionary["val"] = "value"
    convert_dictionary["num"] = "number"
    convert_dictionary["bc"] = "culturale"
    convert_dictionary["pr"] = "ristoro"
    convert_dictionary["col"] = "column"

    return convert_dictionary

def get_remove_list():
    remove_list = []
    remove_list.extend([",", ".", "*", "+", "/", "<", ">", "[", "]", "-"])
    remove_list.extend(["@", "!", ":", ";", "(", ")", "{", "}", "-", "="])
    remove_list.extend(["\'", "\"", "_", "+", "#", "$", "%", "&", "|", "\\"])
    return remove_list

def get_stopword_list():
    stopword_list = []
    stopword_list.extend(["", "abcdefghijklmn"])
    stopword_list.extend(["p"])
    stopword_list.extend(["id", "pid", "name"])
    stopword_list.extend(["nom", "cognome", "nome", "del", "di", "lcon"])
    stopword_list.extend(["relate", "contain", "system"])
    stopword_list.extend(["to", "a", "in", "the", "and"])
    stopword_list.extend(["of", "from", "by", "or", "that"])
    stopword_list.extend(["with", "on", "for", "but", "an"])
    stopword_list.extend(["about", "above", "any", "are", "as"])
    stopword_list.extend(["is", "above", "any", "are", "as"])
    stopword_list.extend(["int", "string", "byte", "double", "boolean"])
    return stopword_list

def get_camelcase_split(identifier_list):
    identifier_split_list = []
    for identifier in identifier_list:
        if identifier.islower():
            identifier_split_list.append(identifier)

        else:
            begin = 0
            for j in range(1, len(identifier)-1):
                if identifier[j].isupper() and identifier[j+1].islower():
                    end = j
                    identifier_split_list.append(identifier[begin:end].lower())
                    begin = end
                if identifier[j:].isupper():
                    end = j
                    identifier_split_list.append(identifier[begin:end].lower())
                    begin = end
                    break

            identifier_split_list.append(identifier[begin:].lower())
    return identifier_split_list


# judge whether it is a number
def is_number(s):
    try:
        float(s)
        return True
    except ValueError:
        pass

    try:
        import unicodedata
        unicodedata.numeric(s)
        return True
    except (TypeError, ValueError):
        pass

    return False


if __name__ == "__main__":
    # get_stopword_list()

    print(is_number("1.9"))

    print()

